---
include:
  - board: xiao_ble
    shield: copen2_R
    # snippet: studio-rpc-usb-uart  # disabled for minimal BLE test
  - board: xiao_ble
    shield: copen2_L
  - board: xiao_ble
    shield: settings_reset
