#Mouse config ---------------------
# CONFIG_PMW3610_INVERT_X=y
# CONFIG_PMW3610_INVERT_Y=y
# CONFIG_PMW3610_SWAP_XY=y
# CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
# CONFIG_PMW3610_LOG_LEVEL_DBG=y
# CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=300 // <--see Troubleshooting

#Encoder config -------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#Layer LED config -------------------
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

// 以下バッテリーや接続、レイヤーの状態でXIAO BLEのLEDを変化させるため
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=250
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=n

CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
#num_cyan
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=6
#sym_yellow
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=3
#jis_white
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=7
#jisnum_cyan
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
#jissys_yellow
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=3
#macarrow_magenta
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=5
#winarrow_magenta
CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=5
#BT_blue
CONFIG_RGBLED_WIDGET_LAYER_8_COLOR=4

#ZMK Studio config -------------------
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

#Bluetooth config -------------------
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12